spring:
  application:
    name: chatGPT

openai:
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions   

server:
  port: 8088
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.web: DEBUG
